import math
from typing import Iterator, Sequence

import cirq
from cirq import X, CCNOT, CNOT

from ..vericirq import GateVerifier, PermutationGate


def _floor_log2(n: int) -> int:
    assert n > 0
    return n.bit_length() - 1


def _parallel_x(qubits: Sequence[cirq.Qid]) -> Iterator[cirq.OP_TREE]:
    for q in qubits:
        yield X(q)


def _parallel_cnot(controls: Sequence[cirq.Qid], targets: Sequence[cirq.Qid]) -> Iterator[cirq.OP_TREE]:
    assert len(controls) == len(targets)
    for control, target in zip(controls, targets):
        yield CNOT(control, target)


def _partition(sizes: Sequence[int], qubits: Sequence[cirq.Qid]) -> list[list[cirq.Qid]]:
    parts: list[list[cirq.Qid]] = []
    offset = 0
    for size in sizes:
        parts.append(list(qubits[offset : offset + size]))
        offset += size
    assert offset == len(qubits)
    return parts


def _prounds(p_workspace: Sequence[Sequence[cirq.Qid]]) -> list[cirq.Operation]:
    ops: list[cirq.Operation] = []
    for i in range(len(p_workspace) - 1):
        current = p_workspace[i][1:]
        nxt = p_workspace[i + 1]
        for m, target in enumerate(nxt):
            ops.append(CCNOT(current[2 * m], current[2 * m + 1], target))
    return ops


def _compute_carries(
    ps: Sequence[cirq.Qid], gs: Sequence[cirq.Qid], workspace: Sequence[cirq.Qid]
) -> list[cirq.Operation]:
    n = len(gs)
    assert len(ps) + 1 == n
    if n <= 1:
        return []

    t_max = _floor_log2(n)
    register_partition = [n // (2**t) - 1 for t in range(1, t_max)]
    p_workspace = [list(ps)] + _partition(register_partition, workspace)

    pround_ops = _prounds(p_workspace)
    ops: list[cirq.Operation] = list(pround_ops)

    # G-rounds.
    for t in range(1, t_max + 1):
        length = n // (2**t) - 1
        ps_t = p_workspace[t - 1][0::2]
        for m in range(length + 1):
            ops.append(CCNOT(gs[2**t * m + 2 ** (t - 1) - 1], ps_t[m], gs[2**t * m + 2**t - 1]))

    # C-rounds.
    start = int(math.floor(math.log2((2 * n) / 3.0)))
    for t in range(start, 0, -1):
        length = (n - 2 ** (t - 1)) // (2**t)
        ps_t = p_workspace[t - 1][1::2]
        for m in range(1, length + 1):
            ops.append(CCNOT(gs[2**t * m - 1], ps_t[m - 1], gs[2**t * m + 2 ** (t - 1) - 1]))

    # Adjoint PRounds.
    ops.extend(reversed(pround_ops))
    return ops


class DraperAdder(PermutationGate):
    """Logarithmic-depth quantum carry-lookahead adder

    Computes: (a, b) := (a, (a+b)%(2^n)).

    Reference:
      A logarithmic-depth quantum carry-lookahead adder.
      Thomas G. Draper, Samuel A. Kutin, Eric M. Rains, Krysta M. Svore.
      https://arxiv.org/abs/quant-ph/0406142

    The gate implementation was generated by Copilot by translating Q# implementation at:
    https://github.com/fedimser/quant-arith-re/blob/main/lib/src/QuantumArithmetic/DKRS2004.qs
    """

    def __init__(self, n: int):
        self.n = n

    @property
    def input_sizes(self):
        # Two registers of size n: (a, b).
        return [self.n, self.n]

    @property
    def ancilla_size(self):
        z_size = max(self.n - 1, 0)
        if z_size <= 1:
            carry_workspace_size = 0
        else:
            carry_workspace_size = z_size - z_size.bit_count() - _floor_log2(z_size)
        return z_size + carry_workspace_size

    def _decompose_(self, qubits: Sequence[cirq.Qid]) -> Iterator[cirq.OP_TREE]:
        n = self.n
        assert len(qubits) == 2 * n + self.ancilla_size
        a, b, anc = qubits[0:n], qubits[n : 2 * n], qubits[2 * n :]

        z_size = max(n - 1, 0)
        z = anc[:z_size]
        carry_workspace = anc[z_size:]

        for i in range(z_size):
            yield CCNOT(a[i], b[i], z[i])

        yield from _parallel_cnot(a, b)

        if n > 1:
            yield from _compute_carries(b[1:z_size], z, carry_workspace)

        yield from _parallel_cnot(z[: n - 1], b[1:n])
        yield from _parallel_x(b[: n - 1])
        yield from _parallel_cnot(a[1 : n - 1], b[1 : n - 1])

        if n > 1:
            yield from reversed(_compute_carries(b[1 : n - 1], z, carry_workspace))

        yield from _parallel_cnot(a[1 : n - 1], b[1 : n - 1])

        for i in range(n - 1):
            yield CCNOT(a[i], b[i], z[i])

        yield from _parallel_x(b[: n - 1])


def verify_draper_adder(adder: DraperAdder):
    """Full formal specification for Draper adder."""
    ver = GateVerifier(adder)
    a_in, b_in = ver.input_vars
    a_out, b_out = ver.output_vars

    # First input is unchanged.
    ver.verify_spec(a_out == a_in).assert_ok()

    # Second input contains the sum modulo 2^n.
    ver.verify_spec(b_out == (a_in + b_in)).assert_ok()

    # Ancillas returned in zero state
    ver.verify_ancillas().assert_ok()
