from typing import Iterator, Sequence

import cirq
import z3
from cirq import CCNOT, CNOT

from ..vericirq import GateVerifier, PermutationGate


def _ctrl_add(
    ctrl: cirq.Qid,
    a: Sequence[cirq.Qid],
    b: Sequence[cirq.Qid],
    z0: cirq.Qid,
    z1: cirq.Qid,
):
    """Controlled adder from MCT2017 section III.

    Computes (under control): b += a, with two helper qubits z0/z1.
    """
    n = len(a)
    assert len(b) == n

    # Step 1.
    for i in range(1, n):
        yield CNOT(a[i], b[i])

    # Step 2.
    yield CCNOT(ctrl, a[n - 1], z0)
    for i in range(n - 2, 0, -1):
        yield CNOT(a[i], a[i + 1])

    # Step 3.
    for i in range(0, n - 1):
        yield CCNOT(b[i], a[i], a[i + 1])

    # Step 4.
    yield CCNOT(b[n - 1], a[n - 1], z1)
    yield CCNOT(ctrl, z1, z0)
    yield CCNOT(b[n - 1], a[n - 1], z1)
    yield CCNOT(ctrl, a[n - 1], b[n - 1])

    # Step 5.
    for i in range(n - 2, -1, -1):
        yield CCNOT(b[i], a[i], a[i + 1])
        yield CCNOT(ctrl, a[i], b[i])

    # Step 6.
    for i in range(1, n - 1):
        yield CNOT(a[i], a[i + 1])

    # Step 7.
    for i in range(1, n):
        yield CNOT(a[i], b[i])


class MctMultiplier(PermutationGate):
    """Multiplies two unsigned integers.

    Computes: (a, b, c) := (a, b, a*b).

    Result register c must be prepared in zero state.

    Reference:
      T-count Optimized Design of Quantum Integer Multiplication
      Edgard Muñoz-Coreas, Himanshu Thapliyal, 2017.
      https://arxiv.org/pdf/1706.05113

    The gate implementation was generated by Copilot by translating Q# implementation at:
    https://github.com/fedimser/quant-arith-re/blob/main/lib/src/QuantumArithmetic/MCT2017.qs
    """

    def __init__(self, n1: int, n2: int):
        """Initializes multiplier with input sizes."""
        self.n1 = n1
        self.n2 = n2

    @property
    def input_sizes(self):
        # Sizes of input registers a, b, c.
        return [self.n1, self.n2, self.n1 + self.n2]

    @property
    def ancilla_size(self):
        return 1

    def _decompose_(self, qubits: Sequence[cirq.Qid]) -> Iterator[cirq.OP_TREE]:
        n1, n2 = self.n1, self.n2
        assert len(qubits) == 2 * (n1 + n2) + 1
        a, b, c = qubits[0:n1], qubits[n1 : n1 + n2], qubits[n1 + n2 : 2 * (n1 + n2)]
        anc = qubits[2 * (n1 + n2)]
        p = list(c) + [anc]

        # Step 1.
        for i in range(n1):
            yield CCNOT(b[0], a[i], p[i])

        # Steps 2-3.
        for i in range(1, n2):
            yield from _ctrl_add(b[i], a, p[i : i + n1], p[i + n1], p[i + n1 + 1])


def verify_mct_multiplier(mult: MctMultiplier):
    """Full formal specification for MCT multiplier."""
    ver = GateVerifier(mult)
    a_in, b_in, c_in = ver.input_vars
    a_out, b_out, c_out = ver.output_vars

    # Precondition: input register must be 0.
    ver.add_precondition(c_in == 0)

    # Inputs are unchanged.
    ver.verify_spec(a_out == a_in).assert_ok()
    ver.verify_spec(b_out == b_in).assert_ok()

    # Result register contains product.
    a_in_ext = z3.ZeroExt(mult.n2, a_in)
    b_in_ext = z3.ZeroExt(mult.n1, b_in)
    ver.verify_spec(c_out == a_in_ext * b_in_ext).assert_ok()

    # Ancillas returned in zero state
    ver.verify_ancillas().assert_ok()
